### ISSUE TITLE
User can view navigation links.

### ISSUE THREAD

**Issue by stephyacek** [stephyacek/sway-finance#3]
# Motivation:
To allow customer to easily navigate to other informative company pages available.

# Tasks:
- [x] add link in nav bar labelled "FAQ"
- [x] add link in nav bar labelled "Security"
- [x] Make links clickable
- [x] Make text correct size/color
- [x] Space links appropriately to the right of the header
