### ISSUE TITLE
User can read the product description.

### ISSUE THREAD

**Issue by stephyacek** [stephyacek/sway-finance#5]
# Motivation:
User needs to be able to read the description of what the website provides.

# Tasks:
- [x] Create container for wording
- [x] Type larger top line of words
- [x] Type smaller lower words
- [x] Line up/change color appropriately
