### ISSUE TITLE
User can view a screenshot of the Sway bot in Slack.

### ISSUE THREAD

**Issue by stephyacek** [stephyacek/sway-finance#7]
# Motivation:
User can see how the product will work with a screenshot.

# Task:
 - [x] Create container for screenshot
- [x] Locate screenshot image and insert in container
 - [x] Resize as needed to center
- [x] Add div around entire blue section
